### PR TITLE
fix macOS electron 3.x compiles

### PR DESCRIPTION
**Pull request by the-j0k3r**
This was broken in https://github.com/microsoft/node-pty/commit/5db10ca4e3970a65492ee0bb7c1f02766d7d6628 made in https://github.com/microsoft/node-pty/pull/322

Consequence macOS builds for electron 3.x fail.

Error logs oof failure  https://travis-ci.org/oznu/node-pty-prebuilt-multiarch/jobs/567184687

Related PR where the issue was first noticed https://github.com/oznu/node-pty-prebuilt-multiarch/pull/2

Progress on issue  comment https://github.com/oznu/node-pty-prebuilt-multiarch/pull/2#issuecomment-517913067

Relevant part of log with error
```log
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:635:10: error: use of undeclared identifier 'openpty'
  return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
         ^
../src/unix/pty.cc:684:10: error: use of undeclared identifier 'forkpty'
  return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
         ^
2 errors generated.
```

With this fix applied compiles are successful once again https://travis-ci.org/the-j0k3r/node-pty-prebuilt-multiarch/jobs/567269847

Notes: Chose node 8.0.0 because node-pty is building from node `8.0.0` up so `8.x` is minimum version.

https://github.com/microsoft/node-pty/blob/32ea3e47791794a82c58c76bf83dc4d441a93108/azure-pipelines.yml#L12

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@Tyriar sorry for shameless ping, but really need this to work upstream.

File: src/unix/pty.cc [hunk 1]
```diff
@@ -34,7 +34,16 @@
 #if defined(__GLIBC__) || defined(__CYGWIN__)
 #include <pty.h>
 #elif defined(__APPLE__) || defined(__OpenBSD__) || defined(__NetBSD__)
+/**
+ * From node v0.10.28 there is also a "util.h" in node/src, which
+ * confuses the compiler when looking for "util.h".
+ * without this compiles of electron 3.x in macOS fail.
+ */
+#if NODE_VERSION_AT_LEAST(8, 0, 0)
```
Comment (Tyriar) [inline src/unix/pty.cc]: Isn't Electron based on node 10?

Comment (the-j0k3r) [reply src/unix/pty.cc]: Yes it is, though as I understand it this is a catch all because the compiler cant find `#include <../include/util.h>` in some cases such as this, simply declaring `#include <util.h>` results in the issue.

I have now changed this to Node 10 with https://github.com/microsoft/node-pty/commit/4f18f21fc4284f6b7517df0380a93f6365b3f230, though. Success build at  https://travis-ci.org/the-j0k3r/node-pty-prebuilt-multiarch/jobs/569183066

The note above the change is the original removed in #322, so the node version here isnt linked to any specific electron build, its just to ensure the compiler finds include its looking for, Anywho changed to 10. =)

**Comment by deepak1556** [comment]
Its a bug in electron for shipping all node src files instead of the necessary header. Electron 3 is no longer a supported release line so fixing there is no longer an option. Also this is fixed in Electron 4 and higher. So I would say the apps should update from electron 3 for the best path forward. I am hesitant to take this path hack since its not needed for the long term.

**Comment by the-j0k3r** [comment]
@deepak1556 Problem is Atom stable 1.39.1 uses electron 3.x and it wont be months before 1.41.0 is shipped and until then we have no working solution fpr the project.

Ill see if the node-pty-prebuilt-multiarch maintainer is willing to carry this patch until then, else Ive no idea.

Thanks either way.

**Comment by the-j0k3r** [comment]
We are going to deal with this another way, We are at the mercy of Atom current production release electron 3.x version until this changes.

Thanks for the consideration. Will close this also =)
