### ISSUE TITLE
The compatibility with electron version?

### ISSUE THREAD

**Issue by KKKZOZ** [microsoft/node-pty#524]
## Environment details

- OS:Windows
- OS version:11
- node-pty version:0.10.1
- electron version: 16.0.0
- node version: 16.13.2

## Issue description
I have tried the example on the project, it works fine for me.
It has following dependecies:
`"dependencies": {
    "electron": "9.1.0",
    "node-pty": "0.9.0",
    "xterm": "4.2.0",
    "xterm-theme": "^1.1.0"
  },`

My current electron project is build on Electron 16.0.0,
so when I change it to 
`"dependencies": {
    "electron": "16.0.0",
    "node-pty": "0.10.1",
    "xterm": "4.2.0",
    "xterm-theme": "^1.1.0"
  },`
There is an error:

>  innerError Error: Cannot find module '../build/Debug/conpty.node'
>  Require stack:
> - C:\Users\KKKZOZ\Desktop\VueProjects\WorkingProject\electron\node_modules\node-pty\lib\windowsPtyAgent.js
>  - C:\Users\KKKZOZ\Desktop\VueProjects\WorkingProject\electron\node_modules\node-pty\lib\windowsTerminal.js
> - C:\Users\KKKZOZ\Desktop\VueProjects\WorkingProject\electron\node_modules\node-pty\lib\index.js
> - C:\Users\KKKZOZ\Desktop\VueProjects\WorkingProject\electron\renderer.js
> - C:\Users\KKKZOZ\Desktop\VueProjects\WorkingProject\electron\index.html
>     at Module._resolveFilename (node:internal/modules/cjs/loader:940)
>     at Function.o._resolveFilename (node:electron/js2c/renderer_init:33)
>     at Module._load (node:internal/modules/cjs/loader:785)
>     at Function.c._load (node:electron/js2c/asar_bundle:5)
>     at Function.o._load (node:electron/js2c/renderer_init:33)
>     at Module.require (node:internal/modules/cjs/loader:1012)
>     at require (node:internal/modules/cjs/helpers:94)
>     at new WindowsPtyAgent (C:\Users\KKKZOZ\Desktop\VueProjects\WorkingProject\electron\node_modules\node-pty\lib\windowsPtyAgent.js:40)
>     at new WindowsTerminal (C:\Users\KKKZOZ\Desktop\VueProjects\WorkingProject\electron\node_modules\node-pty\lib\windowsTerminal.js:50)
>     at Object.spawn (C:\Users\KKKZOZ\Desktop\VueProjects\WorkingProject\electron\node_modules\node-pty\lib\index.js:28)
> 

I have seen other similar issues (like reinstall,electron rebuild) but can not find a solution

Anybody can tell me the corresponding electron version with node-pty 0.10.1 ?

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/node-pty/issues/438

Right now the only Electron versions supported are those with node 14
